# Pipeline de Integração Continua para a disciplina 04 - Integração Contínua para Automação de Testes
# Contemplando o projeto Serviço de Pagamento

name: 'CI - Validação do Serviço de Pagamento'

on:
  workflow_dispatch:
  
  push:
    branches:
      - development

jobs:
  e2e-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando dependências
        run: npm install

      # executar os testes automatizados com relatório
      - name: Executando testes automatizados
        run: npm run test:report

      # salvar relatório de testes
      - name: Salvando relatório de testes
        uses: actions/upload-artifact@v7.0.1
        if: ${{ always() }}
        with:
          path: ./mochawesome-report
          name: Relatório de Testes Mochawesome
          retention-days: 30